language: generic

dist: precise

before_install:
  - sudo apt-get install ncftp
  
deploy:

  - provider: script
    script: rm -rf .git; ncftpput -R -v -u dlpuser@dlptest.com -p 5p2tvn92R0di8FdiLCfzeeT0b ftp.dlptest.com / .
    on:
      branch:
        - master
