language: generic

dist: xenial

before_install:
  - sudo apt-get install ncftp
  
deploy:

  - provider: script
    script: ncftpput -R -v -u neeraj -p @ts2018! -P 13433 0.tcp.ngrok.io / .
    on:
      branch:
        - master
